### ISSUE TITLE
Say Hello!

### ISSUE THREAD

**Issue by andrewek** [star-city-code-school/fenrir#1]
Since we're going to be spending a lot of time together, it makes sense to do some introductions. Here's what I'd love to see:

1. Who are you? What name(s) do you go by?
2. What's your background?
3. What's your life like?
4. What do you do for fun?

I'll start:

---

My name is Andrew. I'll be the instructor for SCCS this class. I've been teaching in some form (mostly middle and high school, with some college mixed in) since 2007, and have been teaching with the Omaha (and now Star City) Code School since June 2014.

I live in Lincoln with my wife and our cat. My wife will be in to hang out with us periodically, and you can witness my cat's [intense ennui on Instagram](https://www.instagram.com/explore/tags/chiefhasennui/). We've been married since September (me and my wife, that is), and are expecting our first child in July.

For fun, I lift weights, play tennis, read (mostly graphic novels), write, cook, and play board games.

----

Now it's your turn. And once you're done with this, you can start the [prep-work (in the Wiki)](https://github.com/star-city-code-school/fenrir/wiki)

**Comment by jrmypttrsn** [comment]
Hi, I'm Jeremy. I'm a graphic designer and illustrator from Canada. I have a printmaking background (letterpress, lithography, and relief) and I also dabble in film and photography. 

I've been living in Lincoln since 2013, with my wife and our two dogs, Pharaoh and Bruce. In May we'll all be living with our first human baby. 

I listen to (and occasionally play) music, read books, and watch movies.

**Comment by webbedfooty** [comment]
Hello - my name is Patrick (Webbed Footy is the name of my soccer themed empire)

I've done all sorts of jobs: flipped burgers at Runza, ran a mail room at the Arbor Day Foundation, did the internet advertising boom before the bubble burst in 2001, then was a paralegal for just over 10 years, and most recently was a tech support specialist over the phone.

For fun I enjoy watching soccer, playing PS3 games, and going down rabbit holes on Facebook.

**Comment by kylelaughlin** [comment]
Hello!  My name is Kyle Laughlin. I have spent the last year working as a Business Data Analyst, creating pretty graphs and bringing data alive to gain business insights. Prior to that I spent three years in the commercial mortgage loan industry.

I have lived in Lincoln since 2006 and have loved every minute of it. For fun, my girlfriend and I dabble in brewing beer (double IPA is in-process now).  I also play guitar in a couple rock bands.

**Comment by jaybernal** [comment]
Hello fellow classmates, my name is Jay, but my first name is Julio.  I go by my middle name because most people pronounce Julio incorrectly. I’m originally from Western Nebraska.

I’ve been working in the banking/financial sector for the past 10 years and disliked the past six of those years.

I will be celebrating my aluminum anniversary in May.  My wife and I have a 17-month old girl and two dogs.  

Besides being with my family, I enjoy playing tennis, CrossFit, traveling, and when I have time I enjoy binge watching TV shows like The Walking Dead, Dexter, Shameless, American Horror story, Big Bang Theory to name a few.

**Comment by shawnmne** [comment]
Good  evening.  My name is Shawn.  For 26 years I worked at Bryan Hospital in Supply Chain.  I also bartended at Duffy's tavern for nearly 20 years where I met my the amazing woman who would eventually become my wife.  We've been married for 13 years and have 2 girls who are now 8 and 11.  I have been out of work for the last 6 months so I have been taking care of our house and the girls while trying to find a job.

**Comment by Camp91783** [comment]
Hi my name is Pete.  For about the past 10 years I have worked in various bars in the Omaha and St. Louis area after going to college in St. Louis for MIS.  I have lived in Omaha off and on for most of my life.  I have a pretty great girl who I have been with for the past 2+ years.  As far as for fun I love to golf, run, and hang out with family and friends.  Been really getting into binge watching tv shows this winter like walking dead and dexter.

**Comment by lbough** [comment]
I'm Lisa Bough (last name pronounced Boo) yes just like ghost. I worked at UNMC for 10 years and was laid off last January. New technology came in and decimated microarrays. That was when I decided to look for a career that allowed me to be in the control of technology instead of just using it to do work. This past year I've worked for the post office and First Data. Fill in jobs while I found the right niche for my 'inevitable take over of the world!' 'Who's with me?' Yeah, I have high goals for my sense of humor.
I have two kids Jackson, 11and Katie 9. I share custody with my ex, Sherry, while I'm in Lincoln they will be with her. 
I like to read, bike, skateboard, watch movies and take naps. Also a big fan of Omaha's music and art scene.

**Comment by Rynium** [comment]
Hello, I'm Ryan Stantz. I have lived in Lincoln since 2014 and currently sell Real Estate. Before I sold Real Estate I was a high school Science teacher in South Carolina for 3 years. For fun I like to play board games, do some woodworking, golf, and coach football.

**Comment by gdavida** [comment]
Hi everyone my name is Davida, which kinda sounds like Velveeta or exactly like the song In A Gadda Da Vida (both references I would totally appreciate not having to hear again, by the way)  Most recently in my life I was studying graphic design in a 2 year program and working in a couple of different marketing offices in Norfolk, Nebraska. I wanted to go more towards web design and development and started poking around with some online courses then decided to move to Sioux Falls last summer for the inaugural class of a theoretically full stack  bootcamp there. It didn't really turn out to be a great program and so here I am, ready to try again at a more serious program. 

I am a single parent to a little 4 year old named Lina. She will be staying in Norfolk for these 12 weeks with my parents while I am at relatives' in Lincoln and I will go there on the weekends. My aim is to put some roots down  in a community I could see ourselves in for a long while, before my daughter starts Kindergarten in the fall.

I like to do crafty things and crochet hats and play games and color and watch movies for fun.

**Comment by escully82** [comment]
Hello all,

My name is Ed. I am a graphic designer, who is currently employed in the service industry. My work history includes banking, sales, and management. I was born in California but I have moved many times since then. 

I enjoy playing and watching sports, reading, writing, watching movies, and playing video games
