### ISSUE TITLE
Week 05, Day 01 - Homework A

### ISSUE THREAD

**Issue by andrewek** [star-city-code-school/fenrir#42]
Clean up your Library Manager project per the videos today. This means:

1. Moving all your models to `app/models`
2. Moving all of your views into subfolders within `views`, e.g. `views/libraries` corresponding to their route.
3. Replacing your `require_relative` statements with the requirement helpers
    + e.g. `Dir[File.dirname(__FILE__) + '/app/models/*.rb'].each {|file| require file }`
4. Ensuring that all of your routes match RESTful conventions, e.g.
   + `/libraries` -> index
   + `/libraries/new` -> new
   + `/libraries/:id` -> show
   + (notice the root of `/libraries` -- plurality is an important part of the convention
5. Ensure that any actions that write to the database are using `post` requests instead of `get` requests.
6. Ensure that you can navigate through the application just by clicking on links and filling out forms (rather than typing URLs manually) and that all links and forms work

If you need an example to work from, here's [my version of this project](https://github.com/star-city-code-school/week-04-library-project/tree/andrew-branch).

**Comment by webbedfooty** [comment]
Running 10 mins late

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 11, 2016 at 8:49 AM, Andrew Ek<notifications@github.com> wrote:   
Clean up your Library Manager project per the videos today. This means:
   
   - Moving all your models to app/models
   - Moving all of your views into subfolders within views, e.g. views/libraries corresponding to their route.
   - Replacing your require_relative statements with the requirement helpers      
      - e.g. Dir[File.dirname(__FILE__) + '/app/models/*.rb'].each {|file| require file }

   - Ensuring that all of your routes match RESTful conventions, e.g.      
      - /libraries -> index
      - /libraries/new -> new
      - /libraries/:id -> show
      - (notice the root of /libraries -- plurality is an important part of the convention

   - Ensure that any actions that write to the database are using post requests instead of get requests.
   - Ensure that you can navigate through the application just by clicking on links and filling out forms (rather than typing URLs manually) and that all links and forms work

If you need an example to work from, here's my version of this project.
