### ISSUE TITLE
W01 D01 Journal Prompt

### ISSUE THREAD

**Issue by andrewek** [star-city-code-school/fenrir#6]
What questions do you have about Ruby? About programming? About problem-solving?

**Comment by webbedfooty** [comment]
How does it compare to Python? Similar structure? Harder/easier?
What are some everyday examples of Ruby coding that I may have encountered?
How long does it take to become a super nano black ninja coder in Ruby?
How long does it take to become a hirable coder in Ruby?

What are the hot languages that are coming on the scene that we should keep an eye on and eventually learn?
Any resources for programming n00bs to help ease the learning curve?

Any resources for helping people change their long-used methods of problem-solving and to introduce new ways to either replace or supplement those methods? Not necessarily Who Moved my Cheese type stuff, but similar

- Patrick

**Comment by jrmypttrsn** [comment]
How is Ruby limited and why? How will we be able to discern if Ruby is the right choice for a given project? Language preferences aside, is Ruby more preferable than php for a large project? 

How often do programmers work in multiple languages? Or do most tend to primarily work in one language?

If a client is dead set on their project being written in a certain language (because of previous projects, they were told that language was best), is it worth trying to convince them to consider another option?

Any further resources relating to systems thinking would be appreciated.

**Comment by kylelaughlin** [comment]
How does the connection between a html webpage, ruby code, and a database work? How does each part communicate and work together to form a fully working application?

Is it common to have multiple languages used on a single project? Like a section in ruby but another piece written in python, java, C++, etc.?

Do you have a methodology when working with clients to obtain their business needs and then break that into software requirements? 

How do you make the call between when something works and when it efficiently works? You mentioned in class that speed is not really the end goal but is there a point when we should be looking for more optimal solutions?

What struggles would you anticipate us having when we move forward from the class and are tasked with learning a new language other than ruby?

**Comment by jaybernal** [comment]
I'm a person who needs to understand how our assignments relate to real world examples.  Im missing that connection 
Can you provide examples of work you have done using ruby and why you used ruby over other languages. 
Does ruby work with WordPress?
What skill sets are are employers in Omaha looking for in Junior Developers?  (ok Lincoln too)
